### ISSUE TITLE
Rehike not working specifically on the home page.

### ISSUE THREAD

**Issue by BrandonisBrandonisBrandon** [Rehike/Rehike#434] opened 2023-11-17 17:15 UTC
I wish to explain that when I first got rehike I had no issue with the home page, and that was for quite a while, but at some point it started showing this error "YukisCoffee\CoffeeRequest\Exception\UncaughtPromiseException: 
  at YukisCoffee\CoffeeRequest\Exception\UncaughtPromiseException::from(Rehike\Exception\Network\InnertubeFailedRequestException)(rehike://modules/YukisCoffee/CoffeeRequest/Exception/UncaughtPromiseException.php:38)
  at YukisCoffee\CoffeeRequest\Promise::reject(Rehike\Exception\Network\InnertubeFailedRequestException)(rehike://modules/YukisCoffee/CoffeeRequest/Promise.php:372)
  at YukisCoffee\CoffeeRequest\Promise::YukisCoffee\CoffeeRequest\{closure}(Rehike\Exception\Network\InnertubeFailedRequestException)(rehike://modules/YukisCoffee/CoffeeRequest/Promise.php:387)
  at Rehike\Network::Rehike\{closure}(YukisCoffee\CoffeeRequest\Network\Response)(rehike://modules/Rehike/Network.php:135)
  at YukisCoffee\CoffeeRequest\Promise::resolve(YukisCoffee\CoffeeRequest\Network\Response)(rehike://modules/YukisCoffee/CoffeeRequest/Promise.php:285)
  at YukisCoffee\CoffeeRequest\Util\QueuedPromiseResolver::finish()(rehike://modules/YukisCoffee/CoffeeRequest/Util/QueuedPromiseResolver.php:57)
  at YukisCoffee\CoffeeRequest\Loop::finishQueuedPromises()(rehike://modules/YukisCoffee/CoffeeRequest/Loop.php:240)
  at YukisCoffee\CoffeeRequest\Loop::cleanup()(rehike://modules/YukisCoffee/CoffeeRequest/Loop.php:230)
  at YukisCoffee\CoffeeRequest\Loop::run()(rehike://modules/YukisCoffee/CoffeeRequest/Loop.php:84)
  at YukisCoffee\CoffeeRequest\Loop::finishQueuedPromises()(rehike://modules/YukisCoffee/CoffeeRequest/Loop.php:244)
  at YukisCoffee\CoffeeRequest\Loop::cleanup()(rehike://modules/YukisCoffee/CoffeeRequest/Loop.php:230)
  at YukisCoffee\CoffeeRequest\Loop::run()(rehike://modules/YukisCoffee/CoffeeRequest/Loop.php:84)
  at YukisCoffee\CoffeeRequest\CoffeeRequest::run()(rehike://modules/YukisCoffee/CoffeeRequest/CoffeeRequest.php:121)
  at Rehike\Network::run()(rehike://modules/Rehike/Network.php:229)
  at Rehike\Controller\core\HitchhikerController::get(Rehike\YtApp, "", Rehike\ControllerV2\RequestMetadata)(rehike://controllers/core/HitchhikerController.php:125)
  at Rehike\ControllerV2\GetControllerInstance::_cv2WrappedCallControllerMethod("get", array<0>)(rehike://modules/Rehike/ControllerV2/GetControllerInstance.php:51)
  at Rehike\ControllerV2\GetControllerInstance::__call("get", array<0>)(rehike://modules/Rehike/ControllerV2/GetControllerInstance.php:74)
  at Rehike\ControllerV2\Router::pointerHandler("feed", "get")(rehike://modules/Rehike/ControllerV2/Router.php:213)
  at Rehike\ControllerV2\Router::baseRequestMethod(array<24>, "get")(rehike://modules/Rehike/ControllerV2/Router.php:157)
  at Rehike\ControllerV2\Router::get(array<24>)(rehike://modules/Rehike/ControllerV2/Router.php:26)
  at require("C:\xampp\htdocs\router.php")(rehike://router.php:77)
  at Rehike\Boot\Bootloader::postboot()(rehike://modules/Rehike/Boot/Bootloader.php:56)
  at Rehike\Boot\Bootloader::startSession()(rehike://modules/Rehike/Boot/Bootloader.php:23)
  at {main}(rehike://index.php:73)"

this is a long error I know, I just don't understand why as It used to be fine.
mind you on any other page (history, watch later, etc.) it works perfectly fine. this specifically only shows up on the home page.

**Comment by YukisCoffee** [comment] 2023-11-17 23:13
Most likely caused by InnerTube server changes. I cannot reproduce this error, so it may take some time to fix.

**Note that if you're running an old version of Rehike, you must update.** The error does not provide sufficient details, but we know of an InnerTube error being thrown by the homepage in older versions due to extra parameters added that we did not support.

I believe you may be running an older version, since newer versions of Rehike should extract the error data in the view in order to provide more details about what went wrong.

I will close this issue, since I have reason to believe that it is already resolved, but you can still comment or reopen it yourself if updating does not solve this problem.

**Closed by YukisCoffee** 2023-11-17 23:13 UTC

**Comment by BrandonisBrandonisBrandon** [comment] 2023-11-29 18:22
after updating rehike the issue has been fixed. thank you for your help!
