### ISSUE TITLE
Live chat not appearing when using native forwarding

### ISSUE THREAD

**Issue by Felting** [Rehike/Rehike#243] opened 2023-02-04 05:50 UTC
Live chat doesn't appear when using native forwarding and shows as a grey box like this:
![image](https://user-images.githubusercontent.com/92234562/216751340-ff70fdf9-235e-4d40-a4ad-a174e03553e2.png)

**Comment by aubymori** [comment] 2023-02-12 22:37
Not enough info, cannot reproduce. Closing.

**Closed by aubymori** 2023-02-12 22:37 UTC
