### ISSUE TITLE
Country code on homepage (missing feature)

### ISSUE THREAD

**Issue by PANMARSAG14** [Rehike/Rehike#163] opened 2022-11-12 08:56 UTC
So, i remember Hitchhiker layout having country codes for specific countries. Is it possible to add this to Rehike?
![chrome_ksq5ahoVwO](https://user-images.githubusercontent.com/81510862/201466801-d7923b57-e8fb-4b3d-81f6-4f0d61ac87b0.png)

**Comment by YukisCoffee** [comment] 2022-11-12 11:26
Duplicate of #71; Rehike currently doesn't support localisation at all, and that includes this part. The country code appears for any country other than the US, but Rehike reports all users as coming from the US at the moment.

**Closed by YukisCoffee** 2022-11-12 11:26 UTC
Labels: bug, duplicate
