### ISSUE TITLE
Live chat request returning error

### ISSUE THREAD

**Issue by Felting** [Rehike/Rehike#275] opened 2023-04-11 23:58 UTC
### Rehike version

0.5

### Operating system

Arch Linux 

### PHP version

8.20

### What's going on?

The live chat request is returning with the error "NS_ERROR_UNEXPECTED". The live chat appears as a white box, I am using the hosts file method.
![image](https://user-images.githubusercontent.com/92234562/231313282-5de539de-87b1-4877-a726-e91cba8323f8.png)
![image](https://user-images.githubusercontent.com/92234562/231313314-3d63f985-1c9b-4e90-9975-d51eedbfa86b.png)

**Comment by Felting** [comment] 2023-08-15 08:57
Update now has this error: ''Exception: Failed to import class controllers/Core/HitchhikerController.php
  at RehikeBase\Autoloader::tryImportClass("controllers/Core/HitchhikerController.php", "Rehike\Controller\Core\HitchhikerController")(rehike://includes/rehike_autoloader.php:110)
  at RehikeBase\Autoloader::autoload("Rehike\Controller\Core\HitchhikerController")(rehike://includes/rehike_autoloader.php:41)
  at require("/opt/lampp/htdocs/controllers/special/get_live_chat.php")(rehike://controllers/special/get_live_chat.php:10)
  at Rehike\ControllerV2\Core::import("controllers/special/get_live_chat.php", <unknown type>)(rehike://modules/Rehike/ControllerV2/Core.php:86)
  at Rehike\ControllerV2\Router::pointerHandler("special/get_live_chat", "get")(rehike://modules/Rehike/ControllerV2/Router.php:195)
  at Rehike\ControllerV2\Router::baseRequestMethod(array<25>, "get")(rehike://modules/Rehike/ControllerV2/Router.php:156)
  at Rehike\ControllerV2\Router::get(array<25>)(rehike://modules/Rehike/ControllerV2/Router.php:26)
  at require("/opt/lampp/htdocs/router.php")(rehike://router.php:81)
  at Rehike\Boot\Bootloader::postboot()(rehike://modules/Rehike/Boot/Bootloader.php:44)
  at Rehike\Boot\Bootloader::startSession()(rehike://modules/Rehike/Boot/Bootloader.php:22)
  at {main}(rehike://index.php:73)

**Comment by YukisCoffee** [comment] 2023-08-15 22:12
FUCKING HELL

This is a case-sensitivity error once again, works on Windows because Windows has a case-insensitive file system, but fails on other operating systems because they have case-sensitive file systems.

Brb

**Comment by YukisCoffee** [comment] 2023-08-15 22:14
Should be fixed in c2f4cc4.

Closing... Reopen if it still doesn't work.

**Comment by Felting** [comment] 2023-08-16 07:08
> Should be fixed in [c2f4cc4](https://github.com/Rehike/Rehike/commit/c2f4cc4482349eac44f3339dbdebf2cbbf046e72).
> 
> Closing... Reopen if it still doesn't work.

Can't reopen because I didn't close it, now shows white box again.

**Comment by YukisCoffee** [comment] 2023-08-16 22:01
Seriously? I thought you could reopen it always.

Can you link a video this happens on? I'll see if I can replicate it.

**Comment by Felting** [comment] 2023-08-16 22:14
> Seriously? I thought you could reopen it always.
> 
> Can you link a video this happens on? I'll see if I can replicate it.

Here is a video it happens on for me: https://www.youtube.com/watch?v=jfKfPfyJRdk it seems to happen on every live stream though.

**Comment by syndiate** [comment] 2023-10-31 02:54
Can't reproduce, probably a network config issue

**Closed by syndiate** 2023-10-31 02:54 UTC
Labels: bug

**Comment by YukisCoffee** [comment] 2023-11-09 06:54
Should be fixed now, actually. It was probably some handling specific to Linux's network stack that rendered our slightly invalid HTTP headers completely invalid and rejected the request.
