### ISSUE TITLE
Subscriptions Missing

### ISSUE THREAD

**Issue by Minebunny99** [Rehike/Rehike#306] opened 2023-06-23 07:22 UTC
### Rehike version

0.7

### Operating system

Windows 10 1903

### PHP version

8.1.17

### What's going on?

Subscriptions on /feed is completely missing

![image](https://github.com/Rehike/Rehike/assets/78270001/2d62a123-91a7-4dab-ba90-69ac44f51b9a)

**Comment by aubymori** [comment] 2023-06-23 07:27
duplicate of #299

**Closed by aubymori** 2023-06-23 07:27 UTC
Labels: bug
