### ISSUE TITLE
Can't watch videos with "The following content may contain suicide or self-harm topics." warning

### ISSUE THREAD

**Issue by MexicanPB** [Rehike/Rehike#327] opened 2023-08-12 01:31 UTC
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.2.0

### What's going on?

Hello, for some reason, I can't watch videos that contain suicide or self-harm topics. Usually, there is a button to skip the message, but it isn't there in ReHike. 
![image](https://github.com/Rehike/Rehike/assets/74111213/f29b1ea3-3a1c-47f9-8ec7-c48ccd6c123f)

**Comment by aubymori** [comment] 2023-08-12 01:31
Duplicate of #43

**Closed by aubymori** 2023-08-12 01:31 UTC
Labels: bug

**Comment by ephemeralViolette** [comment] 2023-08-17 04:05
Fixed now btw :3
