### ISSUE TITLE
Age Restriction warnings are bugged

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#60] opened 2022-08-06 18:04 UTC
On Rehike, Age Restriction warnings are like the "Video Unavailable" warning, you can't watch the video or bypass the warning.
![image](https://user-images.githubusercontent.com/104205144/183260707-3359baa9-989d-4d6b-89b8-831eed22436b.png)

**Comment by aubymori** [comment] 2022-08-06 18:06
Duplicate of #43

**Closed by aubymori** 2022-08-06 18:06 UTC
