### ISSUE TITLE
Cannot bypass warning.

### ISSUE THREAD

**Issue by coffeemccoffeeeeeee** [Rehike/Rehike#281] opened 2023-04-22 19:41 UTC
![image](https://user-images.githubusercontent.com/111658911/233803394-c1803a1b-5125-4ed9-8394-c48d29e77f05.png)

**Comment by YukisCoffee** [comment] 2023-04-22 23:39
Duplicate of #43. Closing...

**Closed by YukisCoffee** 2023-04-22 23:39 UTC
