### ISSUE TITLE
Discord embeds not working

### ISSUE THREAD

**Issue by iamatsomeone** [Rehike/Rehike#263] opened 2023-03-07 03:25 UTC
### Rehike version

0.5

### Operating system

Windows 10 2004, OS Build 19041.1

### PHP version

8.1.10.0

### What's going on?

Embeds on discord do not play video and instead result with an error code
**Warning: Undefined array key 1 in C:\xampp\htdocs\boot.php on line 54**
Screenshot below showing the issue
![Example of the error](https://user-images.githubusercontent.com/101672272/223312570-f4b52c70-4d56-45c4-b457-2b7bfa6b04ea.png)

**Comment by aubymori** [comment] 2023-03-07 03:27
Um, are you fully updated? Because...
![image](https://user-images.githubusercontent.com/44238627/223313033-340ea023-286a-4758-9dd8-08b3cccac797.png)

**Comment by aubymori** [comment] 2023-03-07 03:28
Anyways, embeds work for me.
![image](https://user-images.githubusercontent.com/44238627/223313186-c49630e1-c5db-40ee-81ad-c1b865074ef1.png)

**Comment by iamatsomeone** [comment] 2023-03-07 03:29
I'm on commit 424293b

**Comment by aubymori** [comment] 2023-03-07 03:32
Just pushed a commit that should fix it. Also, you're on 0.5, not 0.7.

**Comment by iamatsomeone** [comment] 2023-03-07 03:33
Oh ok, thanks. And also i didn't know i'm on 0.5 so thanks for that reminder.

**Comment by iamatsomeone** [comment] 2023-03-07 03:38
Now it just appeares black
<img width="147" alt="image" src="https://user-images.githubusercontent.com/101672272/223314625-763b52c2-315d-44b8-809e-d502cadc039b.png">

**Comment by aubymori** [comment] 2023-03-07 03:40
sorry i have literally no idea what the fuck is happening there's no errors or anything

**Comment by iamatsomeone** [comment] 2023-03-07 03:41
no no it's ok my computer is shit or something

**Comment by aubymori** [comment] 2023-03-07 03:41
it's not your computer lol it happens to me too

**Comment by aubymori** [comment] 2023-03-07 03:42
anyways whatever issue is going on here is apparently fixed with 0.7, probably has something to do with the new network system, will close when 0.7 is merged into master

**Comment by iamatsomeone** [comment] 2023-03-07 03:46
<img width="186" alt="image" src="https://user-images.githubusercontent.com/101672272/223315665-1dbdd733-b0c0-4a39-93d8-731d000730f9.png">
this is the console error

**Comment by aubymori** [comment] 2023-03-07 03:49
ok the issue is just suddenly gone for me

**Comment by iamatsomeone** [comment] 2023-03-07 03:50
weird

**Comment by aubymori** [comment] 2023-04-13 21:26
not enough info, doesn't occur for me, inactive thread, closing.

**Comment by aubymori** [comment] 2023-04-23 04:30
happens when rehike certificate isn't installed to the os.

**Comment by YukisCoffee** [comment] 2023-04-23 04:34
Additionally, we will update the documentation to address this. Until then, I will reopen this issue and modify to elaborate.

**Comment by YukisCoffee** [comment] 2023-04-23 04:36
Wait... Wait.

I am very stupid. This is an unrelated issue. Nevermind.

**Closed by YukisCoffee** 2023-04-23 04:36 UTC
Labels: bug
