### ISSUE TITLE
[player/all] Failed to get signature timestamp of player

### ISSUE THREAD

**Issue by TrulyJamal** [Rehike/Rehike#510] opened 2024-02-02 16:27 UTC
![Screenshot (22)](https://github.com/Rehike/Rehike/assets/109087381/6f474c7d-02e2-4658-bb73-2b0475d7c6c1)

**Comment by i-lost-my-bagel** [comment] 2024-02-02 19:56
Need more specifics. What version of rehike are you on? What version of PHP are you using? What OS is it being hosted on?

**Comment by TorutheRedFox** [comment] 2024-02-02 22:30
> Need more specifics. What version of rehike are you on? What version of PHP are you using? What OS is it being hosted on?

and what branch

**Comment by ephemeralViolette** [comment] 2024-02-04 01:00
From reading the error message, one can deduce that this error affects all players, as it's related to signature timestamp retrieval, which is always pulled from the latest player. I have reason to believe that similar errors are occurring related to this problem whereby an exception is not thrown, but further analysis of the problem is necessary.

I have edited the title of this issue and will flag this as a priority issue, since it critically affects the functionality of Rehike.

**Comment by YukisCoffee** [comment] 2024-02-04 11:49
I think that this error is being caused by the player not being requested at all. This seems a rather tentative time. Do you reckon that they could be changing the format of player JS URLs to those weird blob ones like CSS in Polymer uses now?

Anyways, look at the call to `PlayerUpdate::extractSts("")`. Empty quotes, meaning no response was received at all and it just continues chugging along anyways.

I've also heard of an increased report in no internet errors, although I can't replicate them at all myself, so perhaps this is related to that? I wonder why requests are failing for a great number of people all of a sudden.

**Comment by ephemeralViolette** [comment] 2024-02-05 10:55
I can now confirm two things:
- The issue that we were assuming was related (playback throttling in latest player) was caused by code for the classic player being erroneously loaded due to a typo. This has been corrected in 7040a887dc0567fcbe549b8fb9de7854455294e8.
- This issue was also likely fixed in the same commit. Taniko left the debug mode of our backend player code on, which meant that it threw out any cache data. I assume that a rate limit was enforced, so you got no usable data to rerequest the player, and so the crash occurred. Because the cache should be working properly now, I will close this issue.

**Closed by ephemeralViolette** 2024-02-05 10:55 UTC
Labels: bug
