### ISSUE TITLE
"Share" Never Shows

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#68] opened 2022-08-08 08:30 UTC
![image](https://user-images.githubusercontent.com/104205144/183374614-7e417c34-9ab2-456e-86f0-4b70f426a27a.png)
When clicking on the share button, it just never loads.

**Comment by Objectful** [comment] 2022-08-08 10:01
It's not implemented yet

**Comment by aubymori** [comment] 2022-08-08 13:37
duplicate of #62

**Closed by aubymori** 2022-08-08 13:37 UTC
Labels: missing feature
