### ISSUE TITLE
SPF no longer working on navigation

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#346] opened 2023-09-15 19:50 UTC
### Rehike version

0.7

### Operating system

Windows 11 21H2 build 22000.2057

### PHP version

8.1.6

### What's going on?

Pretty self explanatory. SPF doesn't work and throws &spfreload=10 on every url.

**Comment by aubymori** [comment] 2023-09-15 20:25
can't reproduce

**Comment by syndiate** [comment] 2023-09-15 22:43
Please describe the exact circumstances in detail.

**Comment by Felting** [comment] 2023-09-16 00:12
> ### Rehike version
> 
> 0.7
> ### Operating system
> 
> Windows 11 21H2 build 22000.2057
> ### PHP version
> 
> 8.1.6
> ### What's going on?
> 
> Pretty self explanatory. SPF doesn't work and throws &spfreload=10 on every url.

Happening to me also. I fixed it by using [youtube plus](https://github.com/ParticleCore/Particle) and enabling disable spf.

**Comment by Objectful** [comment] 2023-09-16 08:04
[message (10).txt](https://github.com/Rehike/Rehike/files/12640147/message.10.txt)
Here is my ytInitialData dump.

**Comment by YukisCoffee** [comment] 2023-09-18 10:47
Not a YouTube issue, as detailed here. I will close this issue since the same problem is addressed in the linked one:

https://github.com/Rehike/Rehike/issues/347#issuecomment-1723163326

**Closed by YukisCoffee** 2023-09-18 10:47 UTC
Labels: bug
